directory: ~/Desktop/beets-music/

plugins: mbsync fish fuzzy play fetchart

import:
  timid: true
  copy: true
  bell: true
  genres: true

paths:
  default: $albumartist/$album%aunique{}/$track $artist - $title
  singleton: Non-Album/$artist/$artist - $title
  comp: Compilations/$album%aunique{}/$track $artist - $title

sort_item: albumartist+ album+ disc+ track+
