baseurl: ""
url: "http://lpil.uk/"

markdown: kramdown

permalink: "/blog/:title/"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""      # all files
      type: posts   # limit to posts
    values:
      layout: post
