# Site settings
title: lpil
email: louis@lpil.uk
description: The personal website of Louis Pilfold
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:title

exclude:
  - dev_serve.sh
  - Guardfile

sass:
  style: :compact
  sass_dir: _scss
