Metrics/LineLength:
  Max: 80

Style/EmptyLines:
  Enabled: false

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/TrailingComma:
  Enabled: true


# Allow use of empty lines to visually group code into 'paragraphs'
EmptyLines:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
