Metrics/LineLength:
  Max: 80

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma


# Allow use of empty lines to visually group code into 'paragraphs'
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# https://viget.com/extend/just-use-double-quoted-ruby-strings
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/StringLiteralsInInterpolation:
  EnforcedStyle: "double_quotes"
