resources:
- type: compute.v1.instance
  name: vm-my-first-deployment
  properties:
    metadata:
      items:
        - key: deployment
          value: goggles
    zone: us-central1-f
    machineType: https://www.googleapis.com/compute/v1/projects/the-lab-173610/zones/us-central1-f/machineTypes/f1-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-8-jessie-v20160301
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/the-lab-173610/global/networks/default
      # Access Config required to give the instance a public IP address
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
