nonzero_exit_errors = "true"
table_mode = "light"
prompt = "= `{{$(ansi green)}}{{$(prompt-user)}} {{$(ansi yellow)}}{{$(prompt-pwd)}}{{$(do -i { prompt-git })}}{{$(ansi reset)}} > `"
use_starship = false
skip_welcome_message = true
startup = [
  "alias l [a] { ls $a }",
  "alias c [msg] { cd $msg }",
  "alias g [a b c d e f] { git $a $b $c $d $e $f }",
  "alias ga [msg] { git add . }",
  "alias gs [msg] { git status }",
  "alias n [a b c d e f] { nvim $a $b $c $d $e $f }",
  "alias prompt-git [] { git rev-parse --abbrev-ref HEAD | trim | format \" {$(ansi reset)}({$(ansi green)}{$it}{$(ansi reset)})\" }",
  "alias prompt-pwd [] { pwd | str find-replace $(echo '^/home/' $(echo $nu | get env.USER) | str collect) '~' }",
  "alias prompt-user [] { echo $nu | get env.USER }",
]
