# Site settings
title: Perivan Financial
url: http://www.perivanfinancial.co.uk
description: >
  Perivan Financial is the UK’s leading independent financial printer. We are
  entirely owned and run by people who work for the company and our core team
  is without question the most well established in the marketplace.

static: http://www.perivan.co.uk/static

# Contact
email: financial@perivan.co.uk
telephone: +44 (0)20 7562 2278
fax: +44 (0)20 7562 2201
address1: 21 Worship Street
address2: London
address3: EC2A 2DW

# Navigation sections
nav-sections:
  - About
  - Sectors

# Build settings
markdown: kramdown
permalink: /news/:title

exclude:
  - dev_serve.sh
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: :compressed
  sass_dir: _scss

gems:
  - jekyll-sitemap
