# A Job object that will spin up a single short lived pod to perform some
# computation before dying. Database migrations could be run like this.
#
# It's also possible to use multiple pods in a job so that work can be done in
# parallel.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    chapter: jobs
spec:
  template:
    metadata:
      labels:
        chapter: jobs
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:1
          imagePullPolicy: Always
          args:
            - "--keygen-enable"
            - "--keygen-exit-on-complete"
            - "--keygen-num-to-gen=10"
            - "--keygen-exit-code=1" # Make the job fail
      restartPolicy: OnFailure
