name: Record Gleam stats

on:
  schedule:
  # Run every other day at 4am
  - cron: "0 4 */2 * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: erlef/setup-beam@v1.15.2
        with:
          otp-version: "25.2"
          rebar3-version: "3"
          gleam-version: "0.26.0"
      - run: gleam run
        working-directory: scripts/record_gleam_stats
        env:
          GCP_CLIENT_ID: "${{ secrets.GCP_CLIENT_ID }}"
          GCP_CLIENT_SECRET: "${{ secrets.GCP_CLIENT_SECRET }}"
          GCP_REFRESH_TOKEN: "${{ secrets.GCP_REFRESH_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
