name: run

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: "23.2"
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: "0.16.1"
      - run: rebar3 eunit
      # - run: gleam format --check src test
      - run: rebar3 escriptize
      - run: escript _build/default/bin/gh_counts ${{ secrets.GITHUB_TOKEN }}
