name: Sponsorship income to sheets

on:
  schedule:
  # At 03:00 on Saturday.
  - cron: "0 3 * * 6"
  # push:
  #   branches:
  #     - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.9.0
        with:
          otp-version: "23.2"
          gleam-version: "0.21.0"
      - run: gleam run
        working-directory: scripts/sponsorship_income_to_sheets
        env:
          GCP_CLIENT_ID: "${{ secrets.GCP_CLIENT_ID }}"
          GCP_CLIENT_SECRET: "${{ secrets.GCP_CLIENT_SECRET }}"
          GCP_REFRESH_TOKEN: "${{ secrets.GCP_REFRESH_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
