name: Sponsorship income to sheets

on:
  schedule:
  - cron: "0 4 * * 3,6"
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: "25.1"
          rebar3-version: "3"
          gleam-version: "0.25.0"
          # This shouldn't be needed 
          # https://github.com/gleam-lang/gleam/issues/1888
          elixir-version: "1.14.1" 
      - run: gleam run
        working-directory: scripts/sponsorship_income_to_sheets
        env:
          GCP_CLIENT_ID: "${{ secrets.GCP_CLIENT_ID }}"
          GCP_CLIENT_SECRET: "${{ secrets.GCP_CLIENT_SECRET }}"
          GCP_REFRESH_TOKEN: "${{ secrets.GCP_REFRESH_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
