name: pangram
version: 1.0.0.2

dependencies:
  - base

library:
  exposed-modules: Pangram
  source-dirs: src
  dependencies:
  - containers
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
